//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.03 at 11:33:45 AM PST 
//


package org.ndexbio.xbel.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://belframework.org/schema/1.0/xbel}annotation" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://belframework.org/schema/1.0/xbel}evidence" minOccurs="0"/>
 *           &lt;element ref="{http://belframework.org/schema/1.0/xbel}citation" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annotationOrEvidenceOrCitation"
})
@XmlRootElement(name = "annotationGroup")
public class AnnotationGroup {

    @XmlElements({
        @XmlElement(name = "annotation", type = Annotation.class),
        @XmlElement(name = "evidence", type = String.class),
        @XmlElement(name = "citation", type = Citation.class)
    })
    protected List<java.lang.Object> annotationOrEvidenceOrCitation;

    /**
     * Gets the value of the annotationOrEvidenceOrCitation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationOrEvidenceOrCitation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationOrEvidenceOrCitation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Annotation }
     * {@link String }
     * {@link Citation }
     * 
     * 
     */
    public List<java.lang.Object> getAnnotationOrEvidenceOrCitation() {
        if (annotationOrEvidenceOrCitation == null) {
            annotationOrEvidenceOrCitation = new ArrayList<java.lang.Object>();
        }
        return this.annotationOrEvidenceOrCitation;
    }

}
