//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.03 at 11:33:45 AM PST 
//


package org.ndexbio.xbel.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://belframework.org/schema/1.0/xbel}internalAnnotationDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://belframework.org/schema/1.0/xbel}externalAnnotationDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "internalAnnotationDefinition",
    "externalAnnotationDefinition"
})
@XmlRootElement(name = "annotationDefinitionGroup")
public class AnnotationDefinitionGroup {

    protected List<InternalAnnotationDefinition> internalAnnotationDefinition;
    protected List<ExternalAnnotationDefinition> externalAnnotationDefinition;

    /**
     * Gets the value of the internalAnnotationDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internalAnnotationDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInternalAnnotationDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InternalAnnotationDefinition }
     * 
     * 
     */
    public List<InternalAnnotationDefinition> getInternalAnnotationDefinition() {
        if (internalAnnotationDefinition == null) {
            internalAnnotationDefinition = new ArrayList<InternalAnnotationDefinition>();
        }
        return this.internalAnnotationDefinition;
    }

    /**
     * Gets the value of the externalAnnotationDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalAnnotationDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalAnnotationDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalAnnotationDefinition }
     * 
     * 
     */
    public List<ExternalAnnotationDefinition> getExternalAnnotationDefinition() {
        if (externalAnnotationDefinition == null) {
            externalAnnotationDefinition = new ArrayList<ExternalAnnotationDefinition>();
        }
        return this.externalAnnotationDefinition;
    }

}
