//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.03 at 11:33:45 AM PST 
//


package org.ndexbio.xbel.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://belframework.org/schema/1.0/xbel}header"/>
 *         &lt;element ref="{http://belframework.org/schema/1.0/xbel}namespaceGroup" minOccurs="0"/>
 *         &lt;element ref="{http://belframework.org/schema/1.0/xbel}annotationDefinitionGroup" minOccurs="0"/>
 *         &lt;element ref="{http://belframework.org/schema/1.0/xbel}statementGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "namespaceGroup",
    "annotationDefinitionGroup",
    "statementGroup"
})
@XmlRootElement(name = "document")
public class Document {

    @XmlElement(required = true)
    protected Header header;
    protected NamespaceGroup namespaceGroup;
    protected AnnotationDefinitionGroup annotationDefinitionGroup;
    @XmlElement(required = true)
    protected List<StatementGroup> statementGroup;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the namespaceGroup property.
     * 
     * @return
     *     possible object is
     *     {@link NamespaceGroup }
     *     
     */
    public NamespaceGroup getNamespaceGroup() {
        return namespaceGroup;
    }

    /**
     * Sets the value of the namespaceGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamespaceGroup }
     *     
     */
    public void setNamespaceGroup(NamespaceGroup value) {
        this.namespaceGroup = value;
    }

    /**
     * Gets the value of the annotationDefinitionGroup property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationDefinitionGroup }
     *     
     */
    public AnnotationDefinitionGroup getAnnotationDefinitionGroup() {
        return annotationDefinitionGroup;
    }

    /**
     * Sets the value of the annotationDefinitionGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationDefinitionGroup }
     *     
     */
    public void setAnnotationDefinitionGroup(AnnotationDefinitionGroup value) {
        this.annotationDefinitionGroup = value;
    }

    /**
     * Gets the value of the statementGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statementGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatementGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatementGroup }
     * 
     * 
     */
    public List<StatementGroup> getStatementGroup() {
        if (statementGroup == null) {
            statementGroup = new ArrayList<StatementGroup>();
        }
        return this.statementGroup;
    }

}
