//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.03 at 11:33:45 AM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://belframework.org/schema/1.0/xbel", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ndexbio.xbel.model;
