# ── MailHog ───────────────────────────────────────────────────────────────────
[program:mailhog]
command=/usr/local/bin/mailhog
    -smtp-bind-addr 0.0.0.0:1025
    -api-bind-addr 0.0.0.0:8025
    -ui-bind-addr 0.0.0.0:8025
    -auth-file /apps/mailhog/config/auth
    -outgoing-smtp /apps/mailhog/config/outgoing-smtp.json
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
