# ── NDEx (Tomcat) ──────────────────────────────────────────────────────────────
[program:ndex]
command=/usr/local/tomcat/bin/catalina.sh run
environment=ndexConfigurationPath="/apps/ndex/config/ndex.properties",CATALINA_OPTS="-Dlogback.configurationFile=/apps/ndex/config/logback.xml"
priority=30
autostart=true
autorestart=true
startretries=3
startsecs=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
