# ── Solr ──────────────────────────────────────────────────────────────────────
[program:solr]
command=/opt/solr/bin/solr start -f -p 8983 -s /apps/solr/data
environment=SOLR_HOME="/apps/solr/data",SOLR_SECURITY_MANAGER_ENABLED="false",SOLR_MODULES="scripting"
user=solr
priority=20
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
